version: '3'
services:
    frontend:
      build:
        context: .
        dockerfile: ./docker/frontend/Dockerfile
      ports:
        - '80:80'
      depends_on:
        - backend  
      links:
        - "backend:be"
    
    backend:
      build:
        context: .
        dockerfile: ./docker/backend/Dockerfile
      ports:
        - '8000:8000'
      environment:
        - 'NODE_ENV=production'
        - 'GOOGLE_APPLICATION_CREDENTIALS=lyrical-bolt-328905-ca498657da4d.json'